version: "2.2"

services:
  showme_app:
    image: showme_app:latest
    build:
      context: .
      target: runner
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
    user: "1001:1001"
    volumes:
      - ./.next:/app/.next:rw
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
